name: 'GitHub Actions '

on:
  workflow_dispatch:
  schedule:
    - cron: '1 */6 * * *'
jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: 'Set up Python'
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: Get A_JSON
        id: get-accounts
        run: |
          echo "$SERVERS_JSON" > servers.json
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}
      - name: Execute SSH Login Script
        run: |
          python keep.py
