name: keep_serv00

on:
  #schedule:
  #  - cron: '0 */5 * * *'  # 每 5 小时执行一次
  workflow_dispatch:  # 支持手动执行  
  
jobs:
  keep_serv00:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install jq
        run: sudo apt-get install -y jq 

      - name: Get ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$SERVERS_JSON" > servers.json
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}

      - name: Execute SSH Login Script
        run: |
          chmod +x ./keep.sh 
          ./keep.sh
        env:
          PATH: /usr/bin:$PATH
