name: 'KEEP SERV00'

on:
  workflow_dispatch:

jobs:
  server-maintenance-job:
    runs-on: ubuntu-latest  # 选择运行的系统环境，这里选择最新的 Ubuntu 系统，也可按需更换
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取仓库代码到运行环境

      - name: Set up environment variables
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}
        run: |
          echo "$SERVERS_JSON" > servers.txt
      #- name: Install required packages
        #run: |
          #sudo apt-get install -y sshpass curl netcat-openbsd jq  # 安装脚本执行所需的相关工具包，根据实际需要调整安装命令（比如如果是 CentOS 等系统需要用 yum 命令安装）

      - name: Execute KEEP
        run: bash keep.sh  # 执行 keep.sh 脚本，进行服务器相关检测和操作