name: 'KEEP SERV00'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  server-maintenance-job:
    runs-on: ubuntu-latest  # 选择运行的系统环境，这里选择最新的 Ubuntu 系统，也可按需更换
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取仓库代码到运行环境

      - name: Set up environment variables
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}
        run: |
          echo "$SERVERS_JSON" > servers.txt
      #- name: Install required packages
        #run: |
          #sudo apt-get install -y sshpass curl netcat-openbsd jq  # 安装脚本执行所需的相关工具包，根据实际需要调整安装命令（比如如果是 CentOS 等系统需要用 yum 命令安装）

      - name: Execute KEEP
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: bash keep.sh  # 执行 keep.sh 脚本，进行服务器相关检测和操作
     
      - name: Send Telegram Notification
        run: |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "${{ secrets.CHAT_ID }}",
              "text": "GitHub Actions 任务执行完成！\n\n仓库: ${{ github.repository }}\n工作流: ${{ github.workflow }}\n状态: ${{ job.status }}",
              "disable_notification": false
            }' \
            https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage