name: restart

on:
  workflow_dispatch:
  schedule:
   - cron: '0 8 1 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Get ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$SERVERS_JSON" > servers.txt
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}

      - name: Generate SSH Commands
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          while IFS= read -r account; do
            username=$(echo "$account" | cut -d':' -f2)
            password=$(echo "$account" | cut -d':' -f3)
            ssh=$(echo "$account" | cut -d':' -f1)

            # 转义单引号以防止语法错误
            tg_token_escaped=${TG_TOKEN//\'/\'\\\'\'}
            chat_id_escaped=${CHAT_ID//\'/\'\\\'\'}

            echo "echo \"Executing for $ssh\"" >> sshpass.sh
            # 在远程命令中设置环境变量
            echo "sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'export TG_TOKEN='\''$tg_token_escaped'\'' CHAT_ID='\''$chat_id_escaped'\'' && bash <(curl -s https://raw.githubusercontent.com/leung7963/SERV00/main/restart.sh)'" >> sshpass.sh
          done < servers.txt
          chmod +x sshpass.sh
        env:
          TG_TOKEN: ${{ env.TG_TOKEN }}
          CHAT_ID: ${{ env.CHAT_ID }}

      - name: Execute SSH Commands
        run: ./sshpass.sh